spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securitydemo
    username: postgres
    password: ENC(CnQrsyLHYRG6fqQzSPAObg==)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
jasypt:
  encryptor:
    password: dontbookajudgebyitscover1811936582863
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
demo:
  app:
    jwtSecret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    jwtCookieName: mysecurity
    jwtExpirationMs: '86400000'
lease:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://bezkoder-api.com
